### ISSUE TITLE
HTTP Status 401

### ISSUE THREAD

**Issue by cocodrino** [wanasit/everest-js#1]
Hi...I'm trying use everest-js ...I change the config.js with my consumerkey and secret...but when I run I get:

Error getting OAuth request token : { statusCode: 401, data: '
HTTP Status 401 - oauth_consumer_key: cocodrino

type Status report

message oauth_consumer_key: jejeteq

description This request requires HTTP authentication (oauth_consumer_key: cocodrino).
Apache Tomcat/6.0.14

I've tried change evernoteUsedSandbox to true but I still receiving the same error...do you know what can I do??..thanks!!

**Comment by wanasit** [comment]
Hello, Cocodrino

I am hate to tell you this, but receiving this error can only mean there must be something wrong with your consumer key.

Have you ever successfully used this consumer key with any other platform ?

You may need to register for a new consumer key or contact Evernote team.
http://dev.evernote.com/documentation/cloud/

**Comment by zack9433** [comment]
Hi berryboy:

I get the same error with HTTP Status 401 and i register a new consumer key but it doesn't work.

I use the passport-evernote, setting the consumer key and consumer secret and it works......

**Comment by zack9433** [comment]
I found that evernoteUsedSandbox must set to true....

and it just works~

**Comment by cocodrino** [comment]
it's weird, I get a new consumer key and change the evernoteUsedSandbox to true..now seems to work but when I type my evernote username and password I get a message saying these are incorrect  ...I check enter in my evernote web account and the username and password is ok...

**Comment by wanasit** [comment]
Nothing wrong. 

Remember that Evernote's sandbox of each application (and the real server) is separated.
That mean when you create a new consumer key, you need to register a new username/password for its sandbox as well.

(http://dev.evernote.com/documentation/cloud/chapters/Testing.php)

**Comment by cocodrino** [comment]
thanks berry..this works really good...thanks!....
