### ISSUE TITLE
any example for createNote?

### ISSUE THREAD

**Issue by atian25** [wanasit/everest-js#2]

**Comment by wanasit** [comment]
Umm..You are right. There should be an example for createNote. 

I'll make it soon.

**Comment by atian25** [comment]
thanks, waiting~

**Comment by atian25** [comment]
any good news?

**Comment by wanasit** [comment]
Yeah..I just pushed it a few minutes ago.

There is an example website (and a front-end javascript file) that show you how to create notes.
I will find some time to update the document later and clean the code later.
